name: "Feature request"
description: "Suggest a new feature or improvement for the project."
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        # **Feature request**
        Thank you for taking the time to suggest a feature! Please provide as much detail as possible to help us understand and evaluate your request.

        ## **IMPORTANT**
        - For general questions, join our Community-driven [Discord Server](https://discord.gg/6D2dXNy82q).

  - type: checkboxes
    attributes:
      label: Issue Checklist
      options:
        - label: I checked for duplicate issues.
        - label: I searched for existing discussions.
        - label: I checked for an existing pull request that addresses this request.
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Is your feature request related to a problem?
      placeholder: "Provide a clear and concise description of the issue you're facing. Example: 'I'm always frustrated when [...]'"
    validations:
      required: false

  - type: textarea
    id: proposed_solution
    attributes:
      label: Describe the solution you'd like
      placeholder: "Provide a clear and concise description of what you want to happen."
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      placeholder: "Include screenshots, code blocks (use triple backticks ```), or any other relevant information."
    validations:
      required: false